### PR TITLE
Bump parity-common

### PR DESCRIPTION
**Pull request by pgherveou**
Bringing in the changes from https://github.com/paritytech/parity-common/pull/859

### CODE REVIEW

**Comment by pgherveou** [comment]
Hey @vgeddes, would you mind reviewing and publishing this update?

**Review by vgeddes — APPROVED** [review]

**Comment by vgeddes** [comment]
Thanks @pgherveou. Published a new version at https://crates.io/crates/ethabi-decode/1.1.0

**Comment by ordian** [comment]
This should've been published as 2.0 as this is a breaking change.

**Comment by pgherveou** [comment]
> This should've been published as 2.0 as this is a breaking change.

Yeah this might trip up some updates, @vgeddes we should yank it and push 2.0 instead, will push a PR for this

**Comment by ggwpez** [comment]
Yes please, this seems to be breaking. I tried to updated in https://github.com/paritytech/try-runtime-cli and encountered weird build errors.

**Pull request merged**
