### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nazar-pc**
Helps removing duplicated outdated packages from dependency tree

### CODE REVIEW

**Comment by nazar-pc** [comment]
@vgeddes @yrong any concerns about this PR?

**Comment by vgeddes** [comment]
> @vgeddes @yrong any concerns about this PR?

Oh, I must have missed this PR. Thanks @nazar-pc! Will merge it.

**Comment by nazar-pc** [comment]
Thanks!
I see this crate is not on crates.io, which makes it harder to update.
Do you have plans to publish it any time soon?

**Comment by vgeddes** [comment]
Actually, this crate will probably be deprecated, as the upstream ethabi
crate (from which this repo was forked) finally supports no_std.

- Vincent

On May 1, 2023, GitHub ***@***.***> wrote:
> Thanks!
>  I see this crate is not on crates.io, which makes it harder to
> update.
>  Do you have plans to publish it any time soon?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/Snowfork/ethabi-decode/pull/8#issuecomment-
1529922500>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAA4WHTRGEIKJQ2R66OG3SLXD7QETANCNFSM6AAAAAAWQSLAMA>.
You are receiving this because you modified the open/close state.Message
ID: ***@***.***>

**Pull request merged**
